### ISSUE TITLE
Tema Boş Görünüyor

### ISSUE THREAD

**Issue by Barun06** [alihandroo/alihandro.com#1]
[img]http://i.hizliresim.com/dX2D9D.png[/img]

temam boş görünüyor hocam kurulumu nasıl yapılıyor acaba

**Comment by alihandroo** [comment]
Diğer arkadaşlarda kurulumda sorun çıkmamıştı. Eklentileri pasif yapıp öyle deneyebilirmisiniz.

**Comment by alihandroo** [comment]
Sorunun kaynağı wp most popular eklentisinin olmamasından kaynaklanıyormuş. Eklentiyi kurunca sorun çözülüyor.
